modLoader="javafml"
loaderVersion="[${fml_version},)"
license="https://www.gnu.org/licenses/lgpl-3.0.en.html"
issueTrackerURL="https://github.com/Team-Resourceful/ResourcefulBees/issues/new/choose"

[[mods]]
    modId="resourcefulbees"
    version="${version}"
    displayName="Resourceful Bees"
    updateJSONURL="https://api.modrinth.com/updates/jcJ8MbSV/forge_updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/resourceful-bees"
    logoFile="logo.png"
    authors="Epic_Oreo, ThatGravyBoat, Dawn Felstar, (Textures) QBert, (Textures) Joosh"
    description="This mod provides pack makers with useful capabilities for creating custom Resource Bees."

[[dependencies.resourcefulbees]]
    modId="geckolib3"
    mandatory=true
    versionRange="[${gecko_version},)"
    ordering="NONE"
    side="CLIENT"
    [dependencies.resourcefulbees.custom.mc-publish]
        ignore=false
        modrinth="geckolib"
        curseforge="geckolib"

[[dependencies.resourcefulbees]]
    modId="phosphophyllite"
    mandatory=true
    versionRange="[${phos_version},)"
    ordering="NONE"
    side="BOTH"
    [dependencies.resourcefulbees.custom.mc-publish]
        ignore=false
        curseforge="phosphophyllite"

[[dependencies.resourcefulbees]]
    modId="resourcefullib"
    mandatory=true
    versionRange="[${rlib_version},)"
    ordering="NONE"
    side="BOTH"
    [dependencies.resourcefulbees.custom.mc-publish]
        ignore=false
        modrinth="resourceful-lib"
        curseforge="resourceful-lib"

[[dependencies.resourcefulbees]]
    modId="resourcefulconfig"
    mandatory=true
    versionRange="[${rconfig_version},)"
    ordering="NONE"
    side="BOTH"
    [dependencies.resourcefulbees.custom.mc-publish]
        ignore=false
        modrinth="resourceful-config"
        curseforge="resourceful-config"

[[dependencies.resourcefulbees]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.resourcefulbees]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"