modLoader="javafml"
loaderVersion="[34,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/Resourceful-Bees/ResourcefulBees/issues/new/choose"
[[mods]]
modId="resourcefulbees"
version="${file.jarVersion}"
displayName="Resourceful Bees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/resourceful-bees"
logoFile="logo.png"
credits="Thanks to Tfarcenim for making Beesourceful which this mod is heavily based on."
authors="Epic_Oreo, ThatGravyBoat, (Textures) Vik, (Textures) QBert"
description="This mod provides pack makers with useful capabilities for creating custom Resource Bee Types. \n-Special Thanks- \nThanks to the MMD Discord peeps for all of their assistance. \nThanks to Silentchaos512 for his Color Utility."

[[dependencies.resourcefulbees]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.resourcefulbees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"